# Generated by Django 5.0 on 2024-01-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
