# Generated by Django 5.0 on 2024-01-21 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_todo_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
